/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.KiemSoatDeThi_DAO;
import POJO.KiemSoatDeThi_POJO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TAN HUY
 */
public class KiemSoatDeThi extends javax.swing.JFrame {
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    
    static ArrayList<KiemSoatDeThi_POJO> KiemSoatDeThi = KiemSoatDeThi_DAO.LayThongTinDeThi();    
    /**
     * Creates new form KiemSoatDeThi
     */
    public KiemSoatDeThi() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        bangDeThi();
        laydulieuDeThi(KiemSoatDeThi); 
        
        DefaultComboBoxModel<String> modelTrangThaiDeThi = new DefaultComboBoxModel<>();
        modelTrangThaiDeThi.addElement("Mở");
        modelTrangThaiDeThi.addElement("Đóng");
        setComboBoxModel(cbo_trangThai, modelTrangThaiDeThi);
        cbo_trangThai.setSelectedItem("Mở");
        
    }
    private void setComboBoxModel(JComboBox<String> comboBox, DefaultComboBoxModel<String> model) {
        comboBox.setModel(model);
    }
    public void bangDeThi() {
        tblTitle.add("MaDeThi");
        tblTitle.add("NgaySoanDe");
        tblTitle.add("SoLuongCauHoi");
        tblTitle.add("TrangThai");
        tblTitle.add("MaNV");
        tblTitle.add("MaMH");
        tblTitle.add("TrangThaiTruyCapDe");
    }
    public void laydulieuDeThi(ArrayList<KiemSoatDeThi_POJO> KiemSoatDeThi) {
        tblData.removeAllElements();
        for (KiemSoatDeThi_POJO b : KiemSoatDeThi) {
            Vector v = new Vector();
            v.add(b.getMaDeThi());
            v.add(b.getNgaySoanDe());
            v.add(b.getSoLuongCauHoi());
            v.add(b.getTrangThai());
            v.add(b.getMaNV());
            v.add(b.getMaMH());
            v.add(b.getTrangThaiTruyCapDe());
            tblData.add(v);
        }
        tb_deThi.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_deThi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_maDeThi = new javax.swing.JTextField();
        cbo_trangThai = new javax.swing.JComboBox<>();
        bth_capNhat = new javax.swing.JButton();
        btn_troLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("KIỂM SOÁT TRUY CẬP ĐỀ THI");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin đề thi"));

        tb_deThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThongTinDeThi(evt);
            }
        });
        jScrollPane1.setViewportView(tb_deThi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        jLabel2.setText("MÃ ĐỀ THI:");

        jLabel3.setText("TRẠNG THÁI TRUY CẬP ĐỀ THI:");

        bth_capNhat.setText("CẬP NHẬT TRẠNG THÁI");
        bth_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bth_capNhatActionPerformed(evt);
            }
        });

        btn_troLai.setText("TRỞ VỀ");
        btn_troLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_maDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbo_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_troLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bth_capNhat)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_maDeThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bth_capNhat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_troLai))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableThongTinDeThi(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThongTinDeThi
        // Kiểm tra xem người dùng đã chọn hàng chưa
        int rowIndex = tb_deThi.getSelectedRow();
        if (rowIndex >= 0) {
            // Lấy mô hình của bảng
            DefaultTableModel model = (DefaultTableModel) tb_deThi.getModel();

            // Lấy thông tin từ hàng được chọn
            String maDeThi = model.getValueAt(rowIndex, 0).toString();
            Object trangThaiObject = model.getValueAt(rowIndex, 6);

            // Kiểm tra xem giá trị có null không trước khi gán cho combobox
            if (trangThaiObject != null) {
                String trangThai = trangThaiObject.toString();

                // Hiển thị thông tin lên các textfield và combobox tương ứng
                txt_maDeThi.setText(maDeThi);

                // Chọn trạng thái tương ứng trong combobox
                cbo_trangThai.setSelectedItem(trangThai);
            } else {
                // Hiển thị thông tin lên các textfield và combobox tương ứng
                txt_maDeThi.setText(maDeThi);
                // Nếu giá trị là null, bạn có thể thiết lập giá trị mặc định hoặc để combobox không chọn bất kỳ giá trị nào
                cbo_trangThai.setSelectedIndex(-1); // Chọn không có mục nào
            }
        }
    }//GEN-LAST:event_tableThongTinDeThi

    private void bth_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bth_capNhatActionPerformed
        // TODO add your handling code here:
        String maDeThi = txt_maDeThi.getText().trim();
        String trangThai = cbo_trangThai.getSelectedItem().toString().trim();
        String sql = "{CALL NV001.Update_TrangThaiTruyCapDe('"+maDeThi+"','"+trangThai+"')}";
        if(KiemSoatDeThi_DAO.ThemXoaSuaNhanVien(sql) > 0 ){
            JOptionPane.showMessageDialog(this,"Chức năng đã được thực thi","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        ArrayList<KiemSoatDeThi_POJO> kiemSoatDeThi = KiemSoatDeThi_DAO.LayThongTinDeThi(); 
        laydulieuDeThi(kiemSoatDeThi); 
    }//GEN-LAST:event_bth_capNhatActionPerformed

    private void btn_troLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troLaiActionPerformed
        // TODO add your handling code here:
        NhanVien_GUI qtnd = new NhanVien_GUI();
        qtnd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_troLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KiemSoatDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KiemSoatDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KiemSoatDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KiemSoatDeThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KiemSoatDeThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bth_capNhat;
    private javax.swing.JButton btn_troLai;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_deThi;
    private javax.swing.JTextField txt_maDeThi;
    // End of variables declaration//GEN-END:variables
}
