/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.NhanVien_DAO;
import POJO.DBA_PROFILES;
import POJO.DBA_USERS_POJO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TAN HUY
 */
public class Profile_GUI extends javax.swing.JFrame {
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    Vector tblData1 = new Vector();
    Vector tblTitle1 = new Vector();
    
    static ArrayList<DBA_PROFILES> dsProfile =  NhanVien_DAO.LayThongTinProfile();
    static ArrayList<DBA_USERS_POJO> dsUserProfile =  NhanVien_DAO.LayThongTinUserProfile();
    
    /**
     * Creates new form Profile_GUI
     */
    public Profile_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Tài nguyên profile
        bangProfile();
        laydulieuProfile(dsProfile); 
        //user thuộc profile
        bangUserProfile();
        laydulieuUserProfile(dsUserProfile); 
        
        txt_quyen.setText(Login_GUI.chucvu_User);
        txt_quyen.setHorizontalAlignment(SwingConstants.CENTER);
    }
    public void bangProfile() {
        tblTitle.add("PROFILE");
        tblTitle.add("RESOURCE_NAME");
        tblTitle.add("RESOURCE_TYPE");
        tblTitle.add("LIMIT");
    }
    public void bangUserProfile() {
        tblTitle1.add("USERNAME");
        tblTitle1.add("PROFILE");
    }
    public void laydulieuProfile(ArrayList<DBA_PROFILES> dsProfile) {
        tblData.removeAllElements();
        for (DBA_PROFILES b : dsProfile) {
            Vector v = new Vector();
            v.add(b.getPROFILE());
            v.add(b.getRESOURCE_NAME());
            v.add(b.getRESOURCE_TYPE());
            v.add(b.getLIMIT());
            tblData.add(v);
        }
        tb_profile.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    public void laydulieuUserProfile(ArrayList<DBA_USERS_POJO> dsUserProfile) {
        tblData1.removeAllElements();
        for (DBA_USERS_POJO b : dsUserProfile) {
            Vector v = new Vector();
            v.add(b.getUSERNAME());
            v.add(b.getPROFILE());
            tblData1.add(v);
        }
        tb_user_profile.setModel(new DefaultTableModel(tblData1, tblTitle1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tenProfile = new javax.swing.JTextField();
        txt_failed_login_attempts = new javax.swing.JTextField();
        txt_sessions_per_user = new javax.swing.JTextField();
        txt_connect_time = new javax.swing.JTextField();
        txt_idle_time = new javax.swing.JTextField();
        txt_password_lock_time = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_profile = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_user_profile = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_createProfile = new javax.swing.JButton();
        btn_xoaProfile = new javax.swing.JButton();
        btn_suaProfile = new javax.swing.JButton();
        btn_troVe = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txt_nguoiDung = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_ganProfile = new javax.swing.JButton();
        txt_quyen = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Profile");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        jLabel2.setText("TÊN PROFILE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số lần đăng nhập không thành công:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số lượng phiên đăng nhập (sessions) tối đa:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Thời gian kết nối tối đa (theo phút):");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Thời gian không hoạt động tối đa (theo phút):");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Thời gian khóa tài khoản:");

        txt_password_lock_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password_lock_timeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_tenProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(txt_failed_login_attempts)
                    .addComponent(txt_sessions_per_user)
                    .addComponent(txt_connect_time)
                    .addComponent(txt_idle_time)
                    .addComponent(txt_password_lock_time))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_failed_login_attempts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_sessions_per_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_connect_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_idle_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_password_lock_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin các user gán profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        jScrollPane2.setViewportView(tb_profile);

        jScrollPane3.setViewportView(tb_user_profile);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btn_createProfile.setText("TẠO PROFILE");
        btn_createProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createProfileActionPerformed(evt);
            }
        });

        btn_xoaProfile.setText("XÓA PROFILE");
        btn_xoaProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaProfileActionPerformed(evt);
            }
        });

        btn_suaProfile.setText("CẬP NHẬT PROFILE");
        btn_suaProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaProfileActionPerformed(evt);
            }
        });

        btn_troVe.setText("TRỞ VỀ");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gán profile cho ngươi dùng"));

        jLabel8.setText("MÃ NGƯỜI DÙNG:");

        btn_ganProfile.setText("GÁN PROFILE");
        btn_ganProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ganProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_nguoiDung)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btn_ganProfile)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(btn_ganProfile)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_suaProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_createProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoaProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_troVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_createProfile)
                .addGap(18, 18, 18)
                .addComponent(btn_xoaProfile)
                .addGap(18, 18, 18)
                .addComponent(btn_suaProfile)
                .addGap(18, 18, 18)
                .addComponent(btn_troVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_quyen.setEditable(false);
        txt_quyen.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(258, 258, 258)
                .addComponent(txt_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_password_lock_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password_lock_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password_lock_timeActionPerformed

    private void btn_createProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createProfileActionPerformed
        // TODO add your handling code here:
        String tenProfile = txt_tenProfile.getText().trim();
        int failedLoginAttempts = Integer.parseInt(txt_failed_login_attempts.getText().trim());
        int sessionsPerUser = Integer.parseInt(txt_sessions_per_user.getText().trim());
        int connectTime = Integer.parseInt(txt_connect_time.getText().trim());
        int idleTime = Integer.parseInt(txt_idle_time.getText().trim());
        int passwordLockTime = Integer.parseInt(txt_password_lock_time.getText().trim());
        NhanVien_DAO.CreateProfile(tenProfile, failedLoginAttempts, sessionsPerUser, connectTime, idleTime, passwordLockTime);
        JOptionPane.showMessageDialog(this, "Chức năng đã được thực thi", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        ArrayList<DBA_PROFILES> dsWhereProfile =  NhanVien_DAO.LayThongTinWhereProfile(tenProfile);
        //Tài nguyên profile
        laydulieuProfile(dsWhereProfile); 
    }//GEN-LAST:event_btn_createProfileActionPerformed

    private void btn_xoaProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaProfileActionPerformed
        // TODO add your handling code here:
        String tenProfile = txt_tenProfile.getText().trim();
        String sql = "{CALL NV001.DropProfile('"+tenProfile+"')}";
        if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0 ){
            JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        ArrayList<DBA_PROFILES> dsProfile =  NhanVien_DAO.LayThongTinProfile();
        laydulieuProfile(dsProfile); 
        ArrayList<DBA_USERS_POJO> dsUserProfile =  NhanVien_DAO.LayThongTinUserProfile();
        laydulieuUserProfile(dsUserProfile); 
    }//GEN-LAST:event_btn_xoaProfileActionPerformed

    private void btn_suaProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaProfileActionPerformed
        // TODO add your handling code here:
        String tenProfile = txt_tenProfile.getText().trim();
        int failedLoginAttempts = Integer.parseInt(txt_failed_login_attempts.getText().trim());
        int sessionsPerUser = Integer.parseInt(txt_sessions_per_user.getText().trim());
        int connectTime = Integer.parseInt(txt_connect_time.getText().trim());
        int idleTime = Integer.parseInt(txt_idle_time.getText().trim());
        int passwordLockTime = Integer.parseInt(txt_password_lock_time.getText().trim());
        String sql = "{CALL NV001.UpdateProfile('" + tenProfile + "','" + failedLoginAttempts + "','" + sessionsPerUser + "','" + connectTime + "','" + idleTime + "','" + passwordLockTime + "')}";
        if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0 ){
            JOptionPane.showMessageDialog(this,"Chức năng đã được thực thi","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        ArrayList<DBA_PROFILES> dsProfile =  NhanVien_DAO.LayThongTinProfile();
        laydulieuProfile(dsProfile); 
    }//GEN-LAST:event_btn_suaProfileActionPerformed

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        // TODO add your handling code here:
        NhanVien_GUI qtnd = new NhanVien_GUI();
        qtnd.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_troVeActionPerformed

    private void btn_ganProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ganProfileActionPerformed
        // TODO add your handling code here:
        String tenProfile = txt_tenProfile.getText().trim();
        String nguoiDung = txt_nguoiDung.getText().trim();
        
        String sql = "{CALL NV001.AlterProfileToUser('" + nguoiDung + "','" + tenProfile + "')}";
        if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0 ){
            JOptionPane.showMessageDialog(this,"Chức năng đã được thực thi","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        ArrayList<DBA_USERS_POJO> dsUserProfile =  NhanVien_DAO.LayThongTinUserProfile();
        laydulieuUserProfile(dsUserProfile); 
    }//GEN-LAST:event_btn_ganProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createProfile;
    private javax.swing.JButton btn_ganProfile;
    private javax.swing.JButton btn_suaProfile;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JButton btn_xoaProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tb_profile;
    private javax.swing.JTable tb_user_profile;
    private javax.swing.JTextField txt_connect_time;
    private javax.swing.JTextField txt_failed_login_attempts;
    private javax.swing.JTextField txt_idle_time;
    private javax.swing.JTextField txt_nguoiDung;
    private javax.swing.JTextField txt_password_lock_time;
    private javax.swing.JTextField txt_quyen;
    private javax.swing.JTextField txt_sessions_per_user;
    private javax.swing.JTextField txt_tenProfile;
    // End of variables declaration//GEN-END:variables
}
