/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.FGAAuditTrail_DAO;
import DAO.GiamSatSA_DAO;
import DAO.NhanVien_DAO;
import static GUI.FGA_GUI.tenTable;
import POJO.DBA_ROLE_PRIVS;
import POJO.DBA_SYS_PRIVS;
import POJO.GRANTED_ROLE_POJO;
import POJO.Table_POJO;
import POJO.TaiKhoan_POJO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TAN HUY
 */
public class TaoRoleCapQuyenChoRoleNew extends javax.swing.JFrame {
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    
    Vector tblData1 = new Vector();
    Vector tblTitle1 = new Vector();
    
    Vector tblData2 = new Vector();
    Vector tblTitle2 = new Vector();
    
    static ArrayList<GRANTED_ROLE_POJO> dsrole = NhanVien_DAO.LoadDuLieuGRANTED_ROLE();
    static ArrayList<DBA_SYS_PRIVS> ds = NhanVien_DAO.LayThongTinNhanVien2();
    static ArrayList<DBA_ROLE_PRIVS> dsrl = NhanVien_DAO.LayThongTinQuyen();
    /**
     * Creates new form TaoRoleCapQuyenChoRoleNew
     */
    public TaoRoleCapQuyenChoRoleNew() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        bangGRANTED_ROLE();
        laydulieuNV(dsrole);
        
        loadComboBoxLayTable();
        loadComboBoxLayTenRole();
        loadComboBoxUserName_TK();
        
        bangQuyenRole();
        laydulieuQuyenRole(ds);
        
        bangRoleTuongUngVoiNguoiDung();
        laydulieuRoleTuongUngVoiNguoiDung(dsrl);        
    }
    public void bangGRANTED_ROLE() {
        tblTitle.add("Vai trò (Role)");
    }
    public void laydulieuNV(ArrayList<GRANTED_ROLE_POJO> dsROLE) {
        tblData.removeAllElements();
        for (GRANTED_ROLE_POJO b : dsROLE) {
            Vector v = new Vector();
            v.add(b.getGRANTED_ROLE());           
            tblData.add(v);
        }
        tb_dsRole.setModel(new DefaultTableModel(tblData, tblTitle));
    }
    
    public void bangQuyenRole() {
        tblTitle2.add("Đối tượng");
        tblTitle2.add("Người sở hữu");
        tblTitle2.add("Tên bảng");
        tblTitle2.add("Người cấp");
        tblTitle2.add("Quyền");
    }
    public void laydulieuQuyenRole(ArrayList<DBA_SYS_PRIVS> dsg) {
        tblData2.removeAllElements();
        for (DBA_SYS_PRIVS b : dsg) {
            Vector v = new Vector();
            v.add(b.getGRANTEE());
            v.add(b.getOWNER());
            v.add(b.getTABLE_NAME());
            v.add(b.getGRANTOR());
            v.add(b.getPRIVILEGE());
            tblData2.add(v);
        }
        tb_quyenRole.setModel(new DefaultTableModel(tblData2, tblTitle2));
    }
    
    public void bangRoleTuongUngVoiNguoiDung() {
        tblTitle1.add("Người được cấp");
        tblTitle1.add("Tên của vai trò");
        tblTitle1.add("ADMIN_OPTION");
        tblTitle1.add("DELEGATE_OPTION");
        tblTitle1.add("DEFAULT_ROLE");
        tblTitle1.add("COMMON");
    }
    public void laydulieuRoleTuongUngVoiNguoiDung(ArrayList<DBA_ROLE_PRIVS> dsg) {
        tblData1.removeAllElements();
        for (DBA_ROLE_PRIVS b : dsg) {
            Vector v = new Vector();
            v.add(b.getGRANTEE());
            v.add(b.getGRANTED_ROLE());
            v.add(b.getADMIN_OPTION());
            v.add(b.getDELEGATE_OPTION());
            v.add(b.getDEFAULT_ROLE());
            v.add(b.getCOMMON());
            tblData1.add(v);
        }
        tb_roleChoNguoiDung.setModel(new DefaultTableModel(tblData1, tblTitle1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_role = new javax.swing.JTextField();
        btn_taoRole = new javax.swing.JButton();
        bth_xoaRole = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dsRole = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ckb_delete = new javax.swing.JCheckBox();
        ckb_select = new javax.swing.JCheckBox();
        ckb_update = new javax.swing.JCheckBox();
        ckb_insert = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbo_tenRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbo_tenBang = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btn_capRole = new javax.swing.JButton();
        btn_thuRole = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        btn_taiDuLieu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_quyenRole = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbo_tenNguoiDung = new javax.swing.JComboBox<>();
        cbo_tenNhomQuyen = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        btn_capRoleChoNguoiDung = new javax.swing.JButton();
        btn_thuRoleCuaNguoiDung = new javax.swing.JButton();
        btn_timTheoNguoiDung = new javax.swing.JButton();
        btn_taiLaiDLNguoiDungTuongungRole = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_roleChoNguoiDung = new javax.swing.JTable();
        btn_quayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tạo vai trò (role)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên role:");

        btn_taoRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_taoRole.setText("Tạo role");
        btn_taoRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoRoleActionPerformed(evt);
            }
        });

        bth_xoaRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bth_xoaRole.setText("Xóa role");
        bth_xoaRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bth_xoaRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_role)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_taoRole, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(bth_xoaRole, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bth_xoaRole)
                    .addComponent(btn_taoRole))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách các vai trò (role)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jScrollPane1.setViewportView(tb_dsRole);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quyền cho vai trò (role)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        ckb_delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckb_delete.setText("Delete");

        ckb_select.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckb_select.setText("Select");

        ckb_update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckb_update.setText("Update");

        ckb_insert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckb_insert.setText("Insert");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên role:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Thao tác trên bảng:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng cho vai trò (role)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btn_capRole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_capRole.setText("Cấp Quyền Cho Role");
        btn_capRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capRoleActionPerformed(evt);
            }
        });

        btn_thuRole.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_thuRole.setText("Thu Hồi Quyền Của Role");
        btn_thuRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thuRoleActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_timkiem.setText("Tìm kiếm theo tên role");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_taiDuLieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_taiDuLieu.setText("Tải lại dữ liệu ");
        btn_taiDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taiDuLieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_capRole, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_thuRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_taiDuLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capRole)
                    .addComponent(btn_timkiem))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thuRole)
                    .addComponent(btn_taiDuLieu))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckb_update, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckb_select, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ckb_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(ckb_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_tenRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_tenBang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbo_tenRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_tenBang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb_select)
                    .addComponent(ckb_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb_update)
                    .addComponent(ckb_insert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các quyền mà vai trò (role) được cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jScrollPane2.setViewportView(tb_quyenRole);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vai trò (role) cho người dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên người dùng:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên nhóm quyền:");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng cho người dùng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btn_capRoleChoNguoiDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_capRoleChoNguoiDung.setText("Cấp role cho người dùng");
        btn_capRoleChoNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capRoleChoNguoiDungActionPerformed(evt);
            }
        });

        btn_thuRoleCuaNguoiDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_thuRoleCuaNguoiDung.setText("Thu role của người dùng");
        btn_thuRoleCuaNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thuRoleCuaNguoiDungActionPerformed(evt);
            }
        });

        btn_timTheoNguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_timTheoNguoiDung.setText("Tìm kiếm theo người dùng");
        btn_timTheoNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timTheoNguoiDungActionPerformed(evt);
            }
        });

        btn_taiLaiDLNguoiDungTuongungRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_taiLaiDLNguoiDungTuongungRole.setText("Tải lại dữ liệu");
        btn_taiLaiDLNguoiDungTuongungRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taiLaiDLNguoiDungTuongungRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_capRoleChoNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thuRoleCuaNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_timTheoNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_taiLaiDLNguoiDungTuongungRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capRoleChoNguoiDung)
                    .addComponent(btn_timTheoNguoiDung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thuRoleCuaNguoiDung)
                    .addComponent(btn_taiLaiDLNguoiDungTuongungRole))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_tenNguoiDung, 0, 205, Short.MAX_VALUE)
                            .addComponent(cbo_tenNhomQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbo_tenNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbo_tenNhomQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Người dùng với vai trò (role) tương ứng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        jScrollPane3.setViewportView(tb_roleChoNguoiDung);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(14, 14, 14))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_quayLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_quayLai.setText("Trở Về");
        btn_quayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_quayLai)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(btn_quayLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadComboBoxUserName_TK() {
        ArrayList<TaiKhoan_POJO> dsdt = GiamSatSA_DAO.UserName_TK_SelectAll();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (TaiKhoan_POJO dt : dsdt) {
            model.addElement(dt.getUserName_TK());
        }
        cbo_tenNguoiDung.setModel(model);
        cbo_tenNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox cb = (JComboBox) evt.getSource();
            }
        });
    }
    public void loadComboBoxLayTenRole() {
        ArrayList<GRANTED_ROLE_POJO> dsdt = NhanVien_DAO.LoadDuLieuGRANTED_ROLE();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (GRANTED_ROLE_POJO rl : dsdt) {
            model.addElement(rl.getGRANTED_ROLE());
        }
        cbo_tenRole.setModel(model);
        cbo_tenRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox cb = (JComboBox) evt.getSource();
            }
        });
        cbo_tenNhomQuyen.setModel(model);
        cbo_tenNhomQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox cb = (JComboBox) evt.getSource();
            }
        });
    }
    public void loadComboBoxLayTable() {
        ArrayList<Table_POJO> dsdt = FGAAuditTrail_DAO.LayTable();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Table_POJO dt : dsdt) {
            model.addElement(dt.getTABLE_NAME());
        }
        cbo_tenBang.setModel(model);
        cbo_tenBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox cb = (JComboBox) evt.getSource();
            }
        });
    }
    
    private void btn_taoRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoRoleActionPerformed
        // TODO add your handling code here:
        String tenRole = txt_role.getText().trim();
        String sql = "{CALL NV001.create_role_proc('"+tenRole+"')}";
        if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0 ){
            JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        ArrayList<GRANTED_ROLE_POJO> ds = NhanVien_DAO.LoadDuLieuGRANTED_ROLE();
        laydulieuNV(ds);
        loadComboBoxLayTenRole();
    }//GEN-LAST:event_btn_taoRoleActionPerformed

    private void bth_xoaRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bth_xoaRoleActionPerformed
        // TODO add your handling code here:
        String tenRole = txt_role.getText().trim();
        String sql = "{CALL NV001.drop_role_proc('"+tenRole+"')}";
        if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) > 0 ){
            JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        ArrayList<GRANTED_ROLE_POJO> ds = NhanVien_DAO.LoadDuLieuGRANTED_ROLE();
        laydulieuNV(ds);
        loadComboBoxLayTenRole();
    }//GEN-LAST:event_bth_xoaRoleActionPerformed

    private void btn_capRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capRoleActionPerformed
        // TODO add your handling code here:
        String tenBang = cbo_tenBang.getSelectedItem().toString().trim();
        String tenRole = cbo_tenRole.getSelectedItem().toString().trim();

        if (ckb_select.isSelected() || ckb_update.isSelected() || ckb_insert.isSelected() || ckb_delete.isSelected()) {
            if (ckb_select.isSelected()) {
                NhanVien_DAO.capQuyen("SELECT", tenBang, tenRole);
            }
            if (ckb_update.isSelected()) {
                NhanVien_DAO.capQuyen("UPDATE", tenBang, tenRole);
            }
            if (ckb_insert.isSelected()) {
                NhanVien_DAO.capQuyen("INSERT", tenBang, tenRole);
            }
            if (ckb_delete.isSelected()) {
                NhanVien_DAO.capQuyen("DELETE", tenBang, tenRole);
            }
            JOptionPane.showMessageDialog(this, "Thực hiện chức năng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một chức năng", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_capRoleActionPerformed

    private void btn_thuRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thuRoleActionPerformed
        // TODO add your handling code here:
        String tenBang = cbo_tenBang.getSelectedItem().toString().trim();
        String tenRole = cbo_tenRole.getSelectedItem().toString().trim();
        if (ckb_select.isSelected() || ckb_update.isSelected() || ckb_insert.isSelected() || ckb_delete.isSelected()) {
            if (ckb_select.isSelected()) {
                NhanVien_DAO.thuHoiQuyen("SELECT", tenBang, tenRole);
            }
            if (ckb_update.isSelected()) {
                NhanVien_DAO.thuHoiQuyen("UPDATE", tenBang, tenRole);
            }
            if (ckb_insert.isSelected()) {
                NhanVien_DAO.thuHoiQuyen("INSERT", tenBang, tenRole);
            }
            if (ckb_delete.isSelected()) {
                NhanVien_DAO.thuHoiQuyen("DELETE", tenBang, tenRole);
            }
            JOptionPane.showMessageDialog(this, "Thực hiện chức năng thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một chức năng", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_thuRoleActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String tenRole = cbo_tenRole.getSelectedItem().toString().trim();
        if(tenRole.equals(""))
        {
            NhanVien_DAO.LayThongTinNhanVien2();
            ds = NhanVien_DAO.LayThongTinNhanVien2();
            laydulieuQuyenRole(ds);
        }else{
            NhanVien_DAO.LoadDuLieuQuyenNV(tenRole);
            ds = NhanVien_DAO.LoadDuLieuQuyenNV(tenRole);
            laydulieuQuyenRole(ds);
        }    
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_taiDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taiDuLieuActionPerformed
        // TODO add your handling code here:NhanVien_DAO.LayThongTinNhanVien2();
            NhanVien_DAO.LayThongTinNhanVien2();
            ds = NhanVien_DAO.LayThongTinNhanVien2();
            laydulieuQuyenRole(ds);
    }//GEN-LAST:event_btn_taiDuLieuActionPerformed

    private void btn_capRoleChoNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capRoleChoNguoiDungActionPerformed
        // TODO add your handling code here:
        String tenRole = cbo_tenNhomQuyen.getSelectedItem().toString().trim();
        String tennguoidung = cbo_tenNguoiDung.getSelectedItem().toString().trim();
        
        String sql = "{CALL NV001.GrantRoleToUser('" + tenRole + "','" + tennguoidung + "')}";
        if (NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 1) {
            //JOptionPane.showMessageDialog(this, "Thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(this, "Cấp quyền cho user thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } 
        ArrayList<DBA_ROLE_PRIVS> dsrlS = NhanVien_DAO.LayThongTinQuyen();
        laydulieuRoleTuongUngVoiNguoiDung(dsrlS);
    }//GEN-LAST:event_btn_capRoleChoNguoiDungActionPerformed

    private void btn_thuRoleCuaNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thuRoleCuaNguoiDungActionPerformed
        // TODO add your handling code here:
        String tenRole = cbo_tenNhomQuyen.getSelectedItem().toString().trim();
        String tennguoidung = cbo_tenNguoiDung.getSelectedItem().toString().trim();
        
        String sql = "{CALL NV001.RevokeRoleFromUser('" + tenRole + "','" + tennguoidung + "')}";
            int result = NhanVien_DAO.ThemXoaSuaNhanVien(sql);
        if (result == 1) {
            JOptionPane.showMessageDialog(this, "Thu hồi quyền thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("Lỗi khi thực hiện: " + result);
        }
        ArrayList<DBA_ROLE_PRIVS> dsrlS = NhanVien_DAO.LayThongTinQuyen();
        laydulieuRoleTuongUngVoiNguoiDung(dsrlS);
    }//GEN-LAST:event_btn_thuRoleCuaNguoiDungActionPerformed

    private void btn_timTheoNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timTheoNguoiDungActionPerformed
        // TODO add your handling code here:
        String tenNguoiDung = cbo_tenNguoiDung.getSelectedItem().toString().trim();
        ArrayList<DBA_ROLE_PRIVS> tk = NhanVien_DAO.LayThongTinQuyenTheoUser(tenNguoiDung);
        laydulieuRoleTuongUngVoiNguoiDung(tk);
    }//GEN-LAST:event_btn_timTheoNguoiDungActionPerformed

    private void btn_taiLaiDLNguoiDungTuongungRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taiLaiDLNguoiDungTuongungRoleActionPerformed
        // TODO add your handling code here:
        ArrayList<DBA_ROLE_PRIVS> dsrls = NhanVien_DAO.LayThongTinQuyen();
        laydulieuRoleTuongUngVoiNguoiDung(dsrls);
    }//GEN-LAST:event_btn_taiLaiDLNguoiDungTuongungRoleActionPerformed

    private void btn_quayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quayLaiActionPerformed
        // TODO add your handling code here:
        Managanent_GUI qlnv = new Managanent_GUI();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_quayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoRoleCapQuyenChoRoleNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoRoleCapQuyenChoRoleNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoRoleCapQuyenChoRoleNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoRoleCapQuyenChoRoleNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoRoleCapQuyenChoRoleNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bth_xoaRole;
    private javax.swing.JButton btn_capRole;
    private javax.swing.JButton btn_capRoleChoNguoiDung;
    private javax.swing.JButton btn_quayLai;
    private javax.swing.JButton btn_taiDuLieu;
    private javax.swing.JButton btn_taiLaiDLNguoiDungTuongungRole;
    private javax.swing.JButton btn_taoRole;
    private javax.swing.JButton btn_thuRole;
    private javax.swing.JButton btn_thuRoleCuaNguoiDung;
    private javax.swing.JButton btn_timTheoNguoiDung;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cbo_tenBang;
    private javax.swing.JComboBox<String> cbo_tenNguoiDung;
    private javax.swing.JComboBox<String> cbo_tenNhomQuyen;
    private javax.swing.JComboBox<String> cbo_tenRole;
    private javax.swing.JCheckBox ckb_delete;
    private javax.swing.JCheckBox ckb_insert;
    private javax.swing.JCheckBox ckb_select;
    private javax.swing.JCheckBox ckb_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_dsRole;
    private javax.swing.JTable tb_quyenRole;
    private javax.swing.JTable tb_roleChoNguoiDung;
    private javax.swing.JTextField txt_role;
    // End of variables declaration//GEN-END:variables
}
