/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DAO.DAO_KiemTraSession;
import DAO.DBConnect;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Admin
 */
public class TrangChu_GUI extends javax.swing.JFrame {
    public static String username = Login_GUI.loggedInUser;
    private Timer timer;
    private TrangChu_GUI trangChuGUI; // Tham chiếu đến JFrame TrangChu_GUI
    
    /**
     * Creates new form TrangChu_GUI
     */
    public TrangChu_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Account Management");
        
        // Khởi tạo và bắt đầu kiểm tra phiên làm việc
        CheckSessionWorker sessionWorker = new CheckSessionWorker(this);
        sessionWorker.execute(); // Bắt đầu thực thi SwingWorker
        
//        timer = new Timer();
//        scheduleSessionCheck();
    }
    int width=215;
    int hieght=800;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        side = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_trangChu = new javax.swing.JLabel();
        txt_doimatKhau = new javax.swing.JLabel();
        txt_dangKy = new javax.swing.JLabel();
        txt_dangXuat = new javax.swing.JLabel();
        txt_hoTro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_menu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(800, 500));

        side.setBackground(new java.awt.Color(255, 255, 255));
        side.setPreferredSize(new java.awt.Dimension(200, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_app.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        txt_trangChu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_trangChu.setText("Trang chủ");
        txt_trangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_trangChuMouseClicked(evt);
            }
        });

        txt_doimatKhau.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_doimatKhau.setText("Đổi mật khẩu");
        txt_doimatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_doimatKhauMouseClicked(evt);
            }
        });

        txt_dangKy.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_dangKy.setText("Đăng ký");
        txt_dangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_dangKyMouseClicked(evt);
            }
        });

        txt_dangXuat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_dangXuat.setText("Đăng xuất");
        txt_dangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_dangXuatMouseClicked(evt);
            }
        });

        txt_hoTro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_hoTro.setText("Hỗ trợ");
        txt_hoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_hoTroMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_trangChu)
                            .addComponent(txt_doimatKhau)
                            .addComponent(txt_dangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dangXuat)
                            .addComponent(txt_hoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(sideLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(txt_trangChu)
                .addGap(18, 18, 18)
                .addComponent(txt_doimatKhau)
                .addGap(18, 18, 18)
                .addComponent(txt_dangKy)
                .addGap(18, 18, 18)
                .addComponent(txt_dangXuat)
                .addGap(18, 18, 18)
                .addComponent(txt_hoTro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        lbl_menu.setToolTipText("");
        lbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuMouseClicked(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trangchu.jpg"))); // NOI18N

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(7, 7, 7))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Home, "card2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("QUẢN LÝ HỌC SINH BÁN TRÚ");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(side, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addComponent(lbl_menu)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public class CheckSessionWorker extends SwingWorker<Boolean, Void> {
        private final TrangChu_GUI TrangChu_GUI; // Tham chiếu đến JFrame TrangChu_GUI

        public CheckSessionWorker(TrangChu_GUI TrangChu_GUI) {
            this.TrangChu_GUI = TrangChu_GUI;
        }

        @Override
        protected Boolean doInBackground() throws Exception {
            boolean sessionExists = true;
            while (sessionExists) { // Kiểm tra liệu có bị hủy không
                try {
                    String maNV = Login_GUI.loggedInUser;
                    sessionExists = DAO_KiemTraSession.KiemTraSession(maNV);
                } catch (Exception e) {
                    
                }
                Thread.sleep(5000); // Ngủ trong 5 giây
            }
            return sessionExists;
        }

        @Override
        protected void done() {
            try {
                boolean sessionValid = get(); // Lấy kết quả từ doInBackground()
                if (!sessionValid) {
                    // Nếu phiên không còn tồn tại, thông báo và đóng ứng dụng
                    TrangChu_GUI.dispose();
                    System.exit(0);
                }
            } catch (Exception ex) {
                // Xử lý ngoại lệ nếu cần
            }
        }
    }
    
    private void lbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuMouseClicked
        // TODO add your handling code here:
        openMenubar();
    }//GEN-LAST:event_lbl_menuMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        closeMenubar();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_dangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dangXuatMouseClicked
        // TODO add your handling code here:
        // Thông tin kết nối
        String url = "jdbc:oracle:thin:@13.82.232.25:1521:DBHSBT";
        String usernameS = "XacMinhNguoiDung";
        String password = "XacMinhNguoiDung";
        String maNhanVien = Login_GUI.loggedInUser;
        // Khai báo các đối tượng kết nối
        Connection conn = null;
        CallableStatement stmt = null;

        try {
            // Kết nối đến cơ sở dữ liệu
            conn = DriverManager.getConnection(url, usernameS, password);

            // Gọi thủ tục PL/SQL
            String sql = "{ call SYS.DangXuat(?) }";
            stmt = conn.prepareCall(sql);
            stmt.setString(1, maNhanVien); // Truyền tham số vào thủ tục

            // Thực thi thủ tục
            stmt.execute();
            System.out.println("Da ket thuc phien làm viec.");
            
            Login_GUI log = new Login_GUI();
            log.setVisible(true);
            dispose();
        } catch (SQLException e) {
            //e.printStackTrace();
        } finally {
            // Đóng các đối tượng kết nối
            try {
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                //e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txt_dangXuatMouseClicked

    private void txt_doimatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_doimatKhauMouseClicked
        // TODO add your handling code here:
        DoiPass_GUI pass = new DoiPass_GUI();
        pass.setVisible(true);
        dispose();
    }//GEN-LAST:event_txt_doimatKhauMouseClicked

    private void txt_dangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_dangKyMouseClicked
        // TODO add your handling code here:
        String tenchucvu = Login_GUI.chucvu_User;
        if ("Quan Tri He Thong".equals(tenchucvu)) {
            frm_DangKy regA = new frm_DangKy();
            regA.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn không đủ quyền hạn");
        }
    }//GEN-LAST:event_txt_dangKyMouseClicked

    private void txt_trangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_trangChuMouseClicked
        // TODO add your handling code here:
        Managanent_GUI logA = new Managanent_GUI();
        logA.setVisible(true);
        dispose();
    }//GEN-LAST:event_txt_trangChuMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        closeMenubar();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_hoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_hoTroMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Thông tin hỗ trợ sẽ được cập nhật sau");
    }//GEN-LAST:event_txt_hoTroMouseClicked
    
    void closeMenubar(){
        new Thread(new Runnable(){
            @Override
            public void run()
            {
                for(int i=width; i>0;i--)
                {
                    side.setSize(i,hieght);
                       try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            }).start();
    }
    void openMenubar(){
        new Thread(new Runnable(){
            @Override
            public void run()
            {
                for(int i=0; i<width;i++)
                {
                    side.setSize(i,hieght);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(TrangChu_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            }).start();
    }

    public class CustomLogConfig {
        public static void configure() {
            Logger logger = Logger.getLogger("oracle.jdbc");
            logger.setLevel(Level.WARNING); // Đặt mức log mong muốn

            // Vô hiệu hóa console handler
            for (Handler handler : logger.getParent().getHandlers()) {
                if (handler instanceof ConsoleHandler) {
                    logger.getParent().removeHandler(handler);
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {   
                //CustomLogConfig.configure();
                new TrangChu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel side;
    private javax.swing.JLabel txt_dangKy;
    private javax.swing.JLabel txt_dangXuat;
    private javax.swing.JLabel txt_doimatKhau;
    private javax.swing.JLabel txt_hoTro;
    private javax.swing.JLabel txt_trangChu;
    // End of variables declaration//GEN-END:variables
}
